//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicencias {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class env : global::System.Configuration.ApplicationSettingsBase {
        
        private static env defaultInstance = ((env)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new env())));
        
        public static env Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("web-curadurias")]
        public string BUCKETNAME {
            get {
                return ((string)(this["BUCKETNAME"]));
            }
            set {
                this["BUCKETNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AWSACCESSKEY {
            get {
                return ((string)(this["AWSACCESSKEY"]));
            }
            set {
                this["AWSACCESSKEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AWSSECRETKEY {
            get {
                return ((string)(this["AWSSECRETKEY"]));
            }
            set {
                this["AWSSECRETKEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"https://qmap.quspide.co/api/Curadurias/UploadData\"")]
        public string URIMIDAS {
            get {
                return ((string)(this["URIMIDAS"]));
            }
            set {
                this["URIMIDAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cliente1")]
        public string USUARIOMIDAS {
            get {
                return ((string)(this["USUARIOMIDAS"]));
            }
            set {
                this["USUARIOMIDAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12345678")]
        public string PASSWORDMIDAS {
            get {
                return ((string)(this["PASSWORDMIDAS"]));
            }
            set {
                this["PASSWORDMIDAS"] = value;
            }
        }
    }
}
